### ISSUE TITLE
Upgrade Guzzle to 7.0.1

### ISSUE THREAD

**Issue by Thiritin** [ory/hydra-client-php#4]
Laravel Framework requires Guzzle 7.0.1. Can we allow upgrade on this Repo?

**Comment by aeneasr** [comment]
I'm not sure if that would break anything? What does the upgrade process look like for Guzzle?

**Comment by rauanmayemir** [comment]
IIUC, upgrading guzzle has to be done on the `openapi-generator` side, also making sure generators are not using any removed classes or methods, etc.

I'd call dropping php5 support a major change, but I see hydra client already setting php 7.2 as minimal supported version, so that shouldn't be an issue.

While I'm eager do move to guzzle7 myself, I'd say this is a wontfix for this particular package until the 'upstream' tooling does the upgrade.

**Comment by aeneasr** [comment]
Agreed!
